version: '2'

services:
  web:
    build: web
    image: openmrscfldemodistro:1.0.0
    environment:
      DB_DATABASE: openmrs
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CREATE_TABLES: 'false'  # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'false'    # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
      COPY_CFL_MODULES: 'false'
    volumes:
      - web-data:/usr/local/tomcat/.OpenMRS
      - ~/.cfl-dev/modules:/usr/local/tomcat/.OpenMRS/modules/
      - ~/.cfl-dev/owa:/usr/local/tomcat/.OpenMRS/owa/

volumes:
  web-data:
